// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Baseera.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class PhaseB232NoteRoutingAutoAssignment : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "RoutingDecisionId",
                table: "NoteAssignments",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "NoteRoutingRules",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Code = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    NameAr = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    DescriptionAr = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    NoteTypeId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ScopeType = table.Column<int>(type: "int", nullable: false),
                    RegionId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    FacilityId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    FacilityUnitId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    Priority = table.Column<int>(type: "int", nullable: false),
                    ProcessingTargetType = table.Column<int>(type: "int", nullable: false),
                    ProcessingDepartmentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ProcessingRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ReviewerRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DefaultDueDays = table.Column<int>(type: "int", nullable: true),
                    AutoAssignOnSubmit = table.Column<bool>(type: "bit", nullable: false),
                    AutoReassignOnReopen = table.Column<bool>(type: "bit", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    ActivatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    ActivatedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DeactivatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    DeactivatedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    UpdatedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    UpdatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    DeletedBy = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NoteRoutingRules", x => x.Id);
                    table.CheckConstraint("CK_NoteRoutingRules_DefaultDueDays_NonNegative", "[DefaultDueDays] IS NULL OR [DefaultDueDays] >= 0");
                    table.CheckConstraint("CK_NoteRoutingRules_DepartmentTarget", "([ProcessingTargetType] <> 0) OR ([ProcessingDepartmentId] IS NOT NULL AND [ProcessingRoleId] IS NULL)");
                    table.CheckConstraint("CK_NoteRoutingRules_Facility_RequiresFacility", "([ScopeType] <> 3) OR ([RegionId] IS NOT NULL AND [FacilityId] IS NOT NULL AND [FacilityUnitId] IS NULL)");
                    table.CheckConstraint("CK_NoteRoutingRules_GlobalHq_NoIds", "([ScopeType] NOT IN (0, 1)) OR ([RegionId] IS NULL AND [FacilityId] IS NULL AND [FacilityUnitId] IS NULL)");
                    table.CheckConstraint("CK_NoteRoutingRules_Priority_NonNegative", "[Priority] >= 0");
                    table.CheckConstraint("CK_NoteRoutingRules_Region_RequiresRegion", "([ScopeType] <> 2) OR ([RegionId] IS NOT NULL AND [FacilityId] IS NULL AND [FacilityUnitId] IS NULL)");
                    table.CheckConstraint("CK_NoteRoutingRules_RoleTarget", "([ProcessingTargetType] <> 1) OR ([ProcessingRoleId] IS NOT NULL AND [ProcessingDepartmentId] IS NULL)");
                    table.CheckConstraint("CK_NoteRoutingRules_Unit_RequiresFacilityAndUnit", "([ScopeType] <> 4) OR ([RegionId] IS NOT NULL AND [FacilityId] IS NOT NULL AND [FacilityUnitId] IS NOT NULL)");
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Departments_ProcessingDepartmentId",
                        column: x => x.ProcessingDepartmentId,
                        principalTable: "Departments",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Facilities_FacilityId",
                        column: x => x.FacilityId,
                        principalTable: "Facilities",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_FacilityUnits_FacilityUnitId",
                        column: x => x.FacilityUnitId,
                        principalTable: "FacilityUnits",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_NoteTypes_NoteTypeId",
                        column: x => x.NoteTypeId,
                        principalTable: "NoteTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Regions_RegionId",
                        column: x => x.RegionId,
                        principalTable: "Regions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Roles_ProcessingRoleId",
                        column: x => x.ProcessingRoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Roles_ReviewerRoleId",
                        column: x => x.ReviewerRoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Users_ActivatedByUserId",
                        column: x => x.ActivatedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Users_CreatedByUserId",
                        column: x => x.CreatedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Users_DeactivatedByUserId",
                        column: x => x.DeactivatedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRules_Users_UpdatedByUserId",
                        column: x => x.UpdatedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "NoteTypeAccessChangeHistories",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PrincipalType = table.Column<int>(type: "int", nullable: false),
                    PrincipalId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    NoteTypeId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ChangeType = table.Column<int>(type: "int", nullable: false),
                    PreviousCapabilitiesJson = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true),
                    NewCapabilitiesJson = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true),
                    ChangedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    ChangedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    Reason = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    CorrelationId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NoteTypeAccessChangeHistories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_NoteTypeAccessChangeHistories_NoteTypes_NoteTypeId",
                        column: x => x.NoteTypeId,
                        principalTable: "NoteTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteTypeAccessChangeHistories_Users_ChangedByUserId",
                        column: x => x.ChangedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "NoteRoutingDecisions",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    OperationalNoteId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Trigger = table.Column<int>(type: "int", nullable: false),
                    AttemptNumber = table.Column<int>(type: "int", nullable: false),
                    DecisionKey = table.Column<string>(type: "nvarchar(240)", maxLength: 240, nullable: false),
                    RoutingRuleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ResultStatus = table.Column<int>(type: "int", nullable: false),
                    ResolvedDepartmentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ResolvedUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ResolvedProcessingRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ResolvedReviewerRoleId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CreatedAssignmentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DueAtBeforeUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    DueAtAfterUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    DueAtSource = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    DecidedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    DecidedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CorrelationId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    FailureCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    FailureMessageSafe = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    MetadataJson = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NoteRoutingDecisions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_Departments_ResolvedDepartmentId",
                        column: x => x.ResolvedDepartmentId,
                        principalTable: "Departments",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_NoteRoutingRules_RoutingRuleId",
                        column: x => x.RoutingRuleId,
                        principalTable: "NoteRoutingRules",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_OperationalNotes_OperationalNoteId",
                        column: x => x.OperationalNoteId,
                        principalTable: "OperationalNotes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_Roles_ResolvedProcessingRoleId",
                        column: x => x.ResolvedProcessingRoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_Roles_ResolvedReviewerRoleId",
                        column: x => x.ResolvedReviewerRoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_Users_DecidedByUserId",
                        column: x => x.DecidedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingDecisions_Users_ResolvedUserId",
                        column: x => x.ResolvedUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "NoteRoutingRuleHistories",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RoutingRuleId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ChangeType = table.Column<int>(type: "int", nullable: false),
                    SnapshotJson = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: false),
                    ChangedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    ChangedByUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    Reason = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    CorrelationId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NoteRoutingRuleHistories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRuleHistories_NoteRoutingRules_RoutingRuleId",
                        column: x => x.RoutingRuleId,
                        principalTable: "NoteRoutingRules",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_NoteRoutingRuleHistories_Users_ChangedByUserId",
                        column: x => x.ChangedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_NoteAssignments_RoutingDecisionId",
                table: "NoteAssignments",
                column: "RoutingDecisionId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_DecidedByUserId",
                table: "NoteRoutingDecisions",
                column: "DecidedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_DecisionKey",
                table: "NoteRoutingDecisions",
                column: "DecisionKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_OperationalNoteId_DecidedAtUtc",
                table: "NoteRoutingDecisions",
                columns: new[] { "OperationalNoteId", "DecidedAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_ResolvedDepartmentId",
                table: "NoteRoutingDecisions",
                column: "ResolvedDepartmentId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_ResolvedProcessingRoleId",
                table: "NoteRoutingDecisions",
                column: "ResolvedProcessingRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_ResolvedReviewerRoleId",
                table: "NoteRoutingDecisions",
                column: "ResolvedReviewerRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_ResolvedUserId",
                table: "NoteRoutingDecisions",
                column: "ResolvedUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingDecisions_RoutingRuleId_ResultStatus",
                table: "NoteRoutingDecisions",
                columns: new[] { "RoutingRuleId", "ResultStatus" });

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRuleHistories_ChangedByUserId",
                table: "NoteRoutingRuleHistories",
                column: "ChangedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRuleHistories_RoutingRuleId_ChangedAtUtc",
                table: "NoteRoutingRuleHistories",
                columns: new[] { "RoutingRuleId", "ChangedAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_ActivatedByUserId",
                table: "NoteRoutingRules",
                column: "ActivatedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_Code",
                table: "NoteRoutingRules",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_CreatedByUserId",
                table: "NoteRoutingRules",
                column: "CreatedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_DeactivatedByUserId",
                table: "NoteRoutingRules",
                column: "DeactivatedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_FacilityId",
                table: "NoteRoutingRules",
                column: "FacilityId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_FacilityUnitId",
                table: "NoteRoutingRules",
                column: "FacilityUnitId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_NoteTypeId_IsActive_IsDeleted",
                table: "NoteRoutingRules",
                columns: new[] { "NoteTypeId", "IsActive", "IsDeleted" });

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_NoteTypeId_ScopeType_RegionId_FacilityId_FacilityUnitId_Priority_IsDeleted",
                table: "NoteRoutingRules",
                columns: new[] { "NoteTypeId", "ScopeType", "RegionId", "FacilityId", "FacilityUnitId", "Priority", "IsDeleted" },
                unique: true,
                filter: "[RegionId] IS NOT NULL AND [FacilityId] IS NOT NULL AND [FacilityUnitId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_ProcessingDepartmentId",
                table: "NoteRoutingRules",
                column: "ProcessingDepartmentId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_ProcessingRoleId",
                table: "NoteRoutingRules",
                column: "ProcessingRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_RegionId",
                table: "NoteRoutingRules",
                column: "RegionId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_ReviewerRoleId",
                table: "NoteRoutingRules",
                column: "ReviewerRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_ScopeType_RegionId_FacilityId_FacilityUnitId",
                table: "NoteRoutingRules",
                columns: new[] { "ScopeType", "RegionId", "FacilityId", "FacilityUnitId" });

            migrationBuilder.CreateIndex(
                name: "IX_NoteRoutingRules_UpdatedByUserId",
                table: "NoteRoutingRules",
                column: "UpdatedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteTypeAccessChangeHistories_ChangedByUserId",
                table: "NoteTypeAccessChangeHistories",
                column: "ChangedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_NoteTypeAccessChangeHistories_NoteTypeId_ChangedAtUtc",
                table: "NoteTypeAccessChangeHistories",
                columns: new[] { "NoteTypeId", "ChangedAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_NoteTypeAccessChangeHistories_PrincipalType_PrincipalId_ChangedAtUtc",
                table: "NoteTypeAccessChangeHistories",
                columns: new[] { "PrincipalType", "PrincipalId", "ChangedAtUtc" });

            migrationBuilder.AddForeignKey(
                name: "FK_NoteAssignments_NoteRoutingDecisions_RoutingDecisionId",
                table: "NoteAssignments",
                column: "RoutingDecisionId",
                principalTable: "NoteRoutingDecisions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_NoteAssignments_NoteRoutingDecisions_RoutingDecisionId",
                table: "NoteAssignments");

            migrationBuilder.DropTable(
                name: "NoteRoutingDecisions");

            migrationBuilder.DropTable(
                name: "NoteRoutingRuleHistories");

            migrationBuilder.DropTable(
                name: "NoteTypeAccessChangeHistories");

            migrationBuilder.DropTable(
                name: "NoteRoutingRules");

            migrationBuilder.DropIndex(
                name: "IX_NoteAssignments_RoutingDecisionId",
                table: "NoteAssignments");

            migrationBuilder.DropColumn(
                name: "RoutingDecisionId",
                table: "NoteAssignments");
        }
    }
}
