#!/usr/bin/env python3
"""Report likely duplicate integration test scenarios without changing files."""

from __future__ import annotations

import difflib
import pathlib
import re
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parents[1]
TEST_ROOT = ROOT / "src/backend/tests/Baseera.IntegrationTests"


@dataclass(frozen=True)
class TestMethod:
    file: pathlib.Path
    name: str
    endpoints: tuple[str, ...]
    status_assertions: tuple[str, ...]


def extract_tests() -> list[TestMethod]:
    tests: list[TestMethod] = []
    method_pattern = re.compile(
        r"\[(?:IntegrationConnectionFact|Fact|Theory)[^\]]*\]\s+"
        r"public\s+(?:async\s+)?(?:Task|void)\s+(\w+)\s*\(",
        re.MULTILINE,
    )
    endpoint_pattern = re.compile(r'"(/api/v1/[^"\s{}]+)')
    status_pattern = re.compile(r"HttpStatusCode\.(\w+)")

    for path in sorted(TEST_ROOT.glob("*.cs")):
        text = path.read_text(encoding="utf-8")
        matches = list(method_pattern.finditer(text))
        for index, match in enumerate(matches):
            start = match.end()
            end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
            body = text[start:end]
            tests.append(
                TestMethod(
                    file=path.relative_to(ROOT),
                    name=match.group(1),
                    endpoints=tuple(sorted(set(endpoint_pattern.findall(body)))),
                    status_assertions=tuple(sorted(set(status_pattern.findall(body)))),
                )
            )

    return tests


def similar_pairs(tests: list[TestMethod]) -> list[tuple[TestMethod, TestMethod, float]]:
    pairs: list[tuple[TestMethod, TestMethod, float]] = []
    for index, left in enumerate(tests):
        for right in tests[index + 1 :]:
            name_ratio = difflib.SequenceMatcher(None, left.name, right.name).ratio()
            shared_endpoints = set(left.endpoints) & set(right.endpoints)
            shared_statuses = set(left.status_assertions) & set(right.status_assertions)
            endpoint_and_status_overlap = shared_endpoints and shared_statuses and name_ratio >= 0.45
            if left.name == right.name or name_ratio >= 0.82 or endpoint_and_status_overlap:
                pairs.append((left, right, name_ratio))
    return sorted(pairs, key=lambda pair: pair[2], reverse=True)[:50]


def render_report(tests: list[TestMethod]) -> str:
    lines = [
        "# Integration Test Duplication Report",
        "",
        "Generated by `scripts/analyze-integration-tests.py`.",
        "",
        f"Total discovered test methods: {len(tests)}",
        "",
        "## Suspected Groups",
        "",
        "The report is capped at the 50 strongest candidates. `Decision: Keep` means no test was merged automatically.",
        "",
    ]

    pairs = similar_pairs(tests)
    if not pairs:
        lines.append("No suspected duplicate scenarios were detected.")
        return "\n".join(lines) + "\n"

    for left, right, ratio in pairs:
        same_endpoint = bool(set(left.endpoints) & set(right.endpoints))
        same_status = bool(set(left.status_assertions) & set(right.status_assertions))
        lines.extend(
            [
                "### Candidate",
                "",
                f"Files: `{left.file}`, `{right.file}`",
                f"Test names: `{left.name}`, `{right.name}`",
                f"Name similarity: {ratio:.2f}",
                f"Same endpoint? {'Yes' if same_endpoint else 'No'}",
                f"Same status assertion? {'Yes' if same_status else 'No'}",
                "Different permission/scope? Review required",
                "Decision: Keep",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> None:
    tests = extract_tests()
    report = render_report(tests)
    output = ROOT / "docs/integration-test-duplication-report.md"
    output.write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
