namespace Baseera.Application.DependencyInjection;

using Baseera.Application.Abstractions;
using Baseera.Application.Attachments;
using Baseera.Application.Audit;
using Baseera.Application.CorrectiveActions;
using Baseera.Application.Dashboard;
using Baseera.Application.Escalations;
using Baseera.Application.Forms;
using Baseera.Application.Forms.Campaigns;
using Baseera.Application.Forms.Compliance;
using Baseera.Application.Forms.Responses;
using Baseera.Application.Forms.Schema;
using Baseera.Application.Identity;
using Baseera.Application.Notes;
using Baseera.Application.Occupancy;
using Baseera.Application.Organization;
using Baseera.Application.Resources;
using Baseera.Application.Security;
using Baseera.Application.Workforce;
using Baseera.Application.Workspaces;
using FluentValidation;
using Microsoft.Extensions.DependencyInjection;

public static class ApplicationServiceCollectionExtensions
{
    public static IServiceCollection AddBaseeraApplication(this IServiceCollection services)
    {
        services.AddOptions<WorkspaceFrameworkOptions>();
        services.AddValidatorsFromAssemblyContaining<UpdateRegionRequestValidator>();
        services.AddScoped<IOrganizationalScopeService, OrganizationalScopeService>();
        services.AddScoped<IPrivilegeGuard, PrivilegeGuard>();
        services.AddScoped<IOrganizationService, OrganizationService>();
        services.AddScoped<IUserAdminService, UserAdminService>();
        services.AddScoped<IAuditQueryService, AuditQueryService>();
        services.AddScoped<IAttachmentAppService, AttachmentAppService>();
        services.AddScoped<INoteScopeService, NoteScopeService>();
        services.AddScoped<INoteTypeAccessService, NoteTypeAccessService>();
        services.AddScoped<INoteTypeManagementService, NoteTypeManagementService>();
        services.AddScoped<INoteEligibilityService, NoteEligibilityService>();
        services.AddScoped<INoteRoutingService, NoteRoutingService>();
        services.AddScoped<INoteQueryService, NoteQueryService>();
        services.AddScoped<INoteWorkspaceQueryService, NoteWorkspaceQueryService>();
        services.AddScoped<INoteCommandService, NoteCommandService>();
        services.AddScoped<INoteAssignmentService, NoteAssignmentService>();
        services.AddScoped<INoteWorkflowService, NoteWorkflowService>();
        services.AddScoped<IFormScopeService, FormScopeService>();
        services.AddScoped<IFormEffectiveAccessService, FormEffectiveAccessService>();
        services.AddScoped<IFormSeparationOfDutiesService, FormSeparationOfDutiesService>();
        services.AddScoped<IFormRetentionPolicyService, FormRetentionPolicyService>();
        services.AddScoped<IFormGovernanceService, FormGovernanceService>();
        services.AddScoped<IFormQueryService, FormQueryService>();
        services.AddScoped<IFormCommandService, FormCommandService>();
        services.AddScoped<IFormWorkflowService, FormWorkflowService>();
        services.AddScoped<IFormAccessGrantService, FormAccessGrantService>();
        services.AddScoped<IFormSchemaCanonicalizer, FormSchemaCanonicalizer>();
        services.AddScoped<IFormVersionService, FormVersionService>();
        services.AddScoped<IFormTemplateService, FormTemplateService>();
        services.AddScoped<IFormTimeZoneResolver, FormTimeZoneResolver>();
        services.AddScoped<IFormRecurrenceCalculator, FormRecurrenceCalculator>();
        services.AddScoped<IBusinessCalendar, BusinessCalendar>();
        services.AddScoped<IFormTargetResolver, FormTargetResolver>();
        services.AddScoped<IFormCycleGenerationService, FormCycleGenerationService>();
        services.AddScoped<IFormCampaignAccessCoordinator, FormCampaignAccessCoordinator>();
        services.AddScoped<IFormCampaignScheduleCoordinator, FormCampaignScheduleCoordinator>();
        services.AddScoped<IFormCampaignService, FormCampaignService>();
        services.AddScoped<IFormCampaignScheduler, FormCampaignScheduler>();
        services.AddScoped<IFormResponseAccessCoordinator, FormResponseAccessCoordinator>();
        services.AddScoped<IFormResponseAttachmentAccessResolver, FormResponseAttachmentAccessResolver>();
        services.AddScoped<IFormResponseCompletionEvaluator, FormResponseCompletionEvaluator>();
        services.AddScoped<IFormCompletionTimestampResolver, FormCompletionTimestampResolver>();
        services.AddScoped<IFormComplianceQueryService, FormComplianceQueryService>();
        services.AddScoped<IFormResponseValidator, FormResponseValidator>();
        services.AddScoped<IFormResponseProjectionService, FormResponseProjectionService>();
        services.AddScoped<IFormResponseService, FormResponseService>();
        services.AddScoped<IFormResponseReviewService, FormResponseReviewService>();
        services.AddScoped<ICorrectiveActionScopeService, CorrectiveActionScopeService>();
        services.AddScoped<ICorrectiveActionQueryService, CorrectiveActionQueryService>();
        services.AddScoped<ICorrectiveActionCommandService, CorrectiveActionCommandService>();
        services.AddScoped<ICorrectiveActionAssignmentService, CorrectiveActionAssignmentService>();
        services.AddScoped<ICorrectiveActionWorkflowService, CorrectiveActionWorkflowService>();
        services.AddSingleton(TimeProvider.System);
        services.AddScoped<IEscalationPolicyService, EscalationPolicyService>();
        services.AddScoped<IEscalationRuleService>(sp => (EscalationPolicyService)sp.GetRequiredService<IEscalationPolicyService>());
        services.AddScoped<IBackgroundJobLeaseService, BackgroundJobLeaseService>();
        services.AddScoped<IEscalationProcessor, EscalationProcessor>();
        services.AddScoped<INotificationService, NotificationService>();
        services.AddScoped<IEscalationOccurrenceService, EscalationOccurrenceService>();
        services.AddScoped<OperationalDashboardFilterBuilder>();
        services.AddScoped<IOperationalDashboardQueryService, OperationalDashboardQueryService>();
        services.AddScoped<IWorkspaceDefinitionProvider, ReferenceWorkspaceDefinitionProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, OperationalSummaryWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, CorrectiveActionsSummaryWorkspaceWidgetProvider>();
        services.AddScoped<OccupancyService>();
        services.AddScoped<IOccupancyQueryService>(sp => sp.GetRequiredService<OccupancyService>());
        services.AddScoped<IOccupancyCommandService>(sp => sp.GetRequiredService<OccupancyService>());
        services.AddScoped<ResourceReadinessService>();
        services.AddScoped<IResourceReadinessQueryService>(sp => sp.GetRequiredService<ResourceReadinessService>());
        services.AddScoped<IResourceAssetCommandService>(sp => sp.GetRequiredService<ResourceReadinessService>());
        services.AddScoped<IMaintenanceWorkOrderService>(sp => sp.GetRequiredService<ResourceReadinessService>());
        services.AddScoped<IResourceRequirementService>(sp => sp.GetRequiredService<ResourceReadinessService>());
        services.AddScoped<IResourceImportService>(sp => sp.GetRequiredService<ResourceReadinessService>());
        services.AddSingleton<IWorkforceSourceResolver, WorkforceSourceResolver>();
        services.AddScoped<WorkforceReadinessService>();
        services.AddScoped<IWorkforceReadinessQueryService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceMemberCommandService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IStaffingRequirementService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IDutyRosterService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceAvailabilityService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceImportService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceReconciliationService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceMemberQueryService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceExportService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<IWorkforceCriticalPositionQueryService>(sp => sp.GetRequiredService<WorkforceReadinessService>());
        services.AddScoped<FacilityWorkspaceFacilityDomainQueries>();
        services.AddScoped<IFacilityWorkspaceReadService, FacilityWorkspaceReadService>();
        services.AddScoped<IWorkspaceDefinitionProvider, FacilityWorkspaceDefinitionProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityHeaderWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityExecutiveSummaryWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityNotesOverviewWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityCorrectiveActionsWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityAlertsEscalationsWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityFormComplianceWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityPriorityQueueWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityOccupancyWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityResourcesWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityWorkforceWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityRecentActivityWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityStructureWorkspaceWidgetProvider>();
        services.AddScoped<IWorkspaceWidgetProvider, FacilityDataQualityWorkspaceWidgetProvider>();
        services.AddScoped<WorkspaceContextResolver>();
        services.AddScoped<IWorkspaceRegistry, WorkspaceRegistry>();
        services.AddScoped<IWorkspaceQueryService, WorkspaceQueryService>();
        return services;
    }
}
